spring:
  application:
    name: capsicum-anuumm-api
  profiles:
    active: @activatedProperties@
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CAPSICUM_DB_HOST}:5432/${CAPSICUM_DB}?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    
server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
