spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://dgzlbwrxvloomc:a8157c9ca06b962d04d4c0c31a468f7936511ac030d860489507d74f4d134ace@ec2-23-20-129-146.compute-1.amazonaws.com:5432/d7teblgjmk304n
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
