annuum:
  image-repo:
      url: https://annuum-image-api-homolog.herokuapp.com/
      token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXBzaWN1dW0tYW5udXVtIiwiaWF0IjoxNTkzMzcwNTkwLCJleHAiOjQwODYzNTYxOTAsImF1ZCI6IiIsInN1YiI6ImNhcHNpY3V1bS1hbm51dW0tYXBwLWhvbW9sb2cifQ.Z9tU8jf4sgnxTB4cedYwblfcNwzIHVQhR7hE3TLHypg
  security:
    cors:
      allowed-origins: "*"
    jwt:
      secret: "MTIzNDU2"
      expiration: 43200 # 30 dias em minutos
spring:
  application:
    name: capsicum-anuumm-api
  profiles:
    active: @activatedProperties@
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CAPSICUM_DB_HOST}:5432/${CAPSICUM_DB}?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    initialization-mode: always
    hikari:
      maximum-pool-size: 2
server:
  servlet:
    context-path: "/annuum-api"
