spring:
  application:
    name: capsicum-anuumm-api
  profiles:
    active: @activatedProperties@
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CAPSICUM_DB_HOST:ec2-23-20-129-146.compute-1.amazonaws.com}:5432/d7teblgjmk304n?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: ${secrets.DB_USERNAME:dgzlbwrxvloomc}
    password: ${secrets.DB_PASSWORD:a8157c9ca06b962d04d4c0c31a468f7936511ac030d860489507d74f4d134ace}

server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
