annuum:
  security:
    cors:
      allowed-origins: "*"
    jwt:
      secret: "123456"
      expiration: 43200 # 30 dias em minutos
spring:
  application:
    name: capsicum-anuumm-api
  profiles:
    active: @activatedProperties@
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${CAPSICUM_DB_HOST}:5432/${CAPSICUM_DB}?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}
    hikari:
      maximum-pool-size: 2
server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
