spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-18-215-99-63.compute-1.amazonaws.com:5432/d7malmvd5vlhot?user=qfsjzsfjnnwswl&password=9cb4ca8a36393002e254d356539c1cf3961e8b683f74877b2c85387b0adb1641
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}

server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
