spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://dgzlbwrxvloomc:a8157c9ca06b962d04d4c0c31a468f7936511ac030d860489507d74f4d134ace@ec2-23-20-129-146.compute-1.amazonaws.com:5432/d7teblgjmk304n
    username: ygmfurlunobgmc
    password: a23f12974620e6cbbb8e502136e7ffc3e62cc1fa67bfc11d7cff7ab6ef0462d9

server:
  port: 8080
  servlet:
    context-path: "/annuum-api"
